# Generated by Django 5.2.7 on 2025-11-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia', models.TextField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estudios', models.CharField(choices=[('PR', 'Primaria'), ('SE', 'Secundaria'), ('UN', 'Universidad'), ('OT', 'Otro')], max_length=2)),
                ('institucion_actual', models.CharField(max_length=255)),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('jerarquia', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'constraints': [models.CheckConstraint(check=models.Q(jerarquia__gte=1, jerarquia__lte=5), name='rol_jerarquia_entre_1_y_5')],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tutor', models.CharField(choices=[('AC', 'Academico'), ('PE', 'Personal'), ('LA', 'Laboral'), ('OT', 'Otro')], max_length=2)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('disponibilidad_horaria', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rol')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TutorEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor_legal', 'Tutor Legal'), ('abuelo', 'Abuelo/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Parentesco')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='roles.estudiante', verbose_name='Estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_a_cargo', to='roles.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Relación Tutor-Estudiante',
                'verbose_name_plural': 'Relaciones Tutor-Estudiante',
                'unique_together': {('tutor', 'estudiante')},
            },
        ),
    ]
