# Generated by Django 5.2.7 on 2025-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_estudios',
            field=models.CharField(choices=[('PI', 'Primaria Incompleto'), ('PR', 'Primaria Completo'), ('SI', 'Secundaria Incompleto'), ('SE', 'Secundaria Completo'), ('UI', 'Universidad Incompleto'), ('UN', 'Universidad Completo'), ('OT', 'Otro')], max_length=2),
        ),
    ]
