# Generated by Django 5.2.7 on 2025-12-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_estudiante_nivel_estudios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorestudiante',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor_legal', 'Tutor Legal'), ('abuelo', 'Abuelo/a'), ('hermano', 'Hermano/a'), ('vecino', 'Vecino/a')], max_length=20, null=True, verbose_name='Parentesco'),
        ),
    ]
