# Generated by Django 5.2.7 on 2025-12-22 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_tutorestudiante_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizadoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor_legal', 'Tutor Legal'), ('abuelo', 'Abuelo/a'), ('hermano', 'Hermano/a'), ('vecino', 'Vecino/a'), ('otro', 'Otro')], max_length=20)),
                ('confirmado', models.BooleanField(default=False)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('revocado', models.BooleanField(default=False)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados_retiro', to='roles.estudiante')),
            ],
            options={
                'verbose_name': 'Autorizado para Retirar',
                'verbose_name_plural': 'Autorizados para Retirar',
                'unique_together': {('estudiante', 'dni')},
            },
        ),
    ]
