# Generated by Django 5.2.7 on 2025-11-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clases', models.IntegerField(default=0, verbose_name='Total de Clases')),
                ('clases_asistidas', models.IntegerField(default=0, verbose_name='Clases Asistidas')),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% de Asistencia')),
                ('cumple_requisito_certificado', models.BooleanField(default=False, verbose_name='Cumple Requisito para Certificado')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_asistencia', to='inscripciones.inscripcion', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_clase', models.DateField(verbose_name='Fecha de la Clase')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='inscripciones.inscripcion', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_clase'],
                'unique_together': {('inscripcion', 'fecha_clase')},
            },
        ),
    ]
