# Generated by Django 5.2.7 on 2025-11-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Inscripción')),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('lista_espera', 'En Lista de Espera'), ('cancelada', 'Cancelada')], default='confirmado', max_length=20, verbose_name='Estado')),
                ('orden_lista_espera', models.IntegerField(blank=True, null=True, verbose_name='Orden en Lista de Espera')),
                ('observaciones_discapacidad', models.TextField(blank=True, null=True, verbose_name='Observaciones de Discapacidad')),
                ('observaciones_salud', models.TextField(blank=True, null=True, verbose_name='Observaciones de Salud (celíaco, alergias, etc.)')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.comision', verbose_name='Comisión')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='roles.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['orden_lista_espera', '-fecha_hora_inscripcion'],
                'unique_together': {('estudiante', 'comision')},
            },
        ),
    ]
