# Generated by Django 5.2.7 on 2025-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pre_inscripto', 'Pre-Inscripto'), ('confirmado', 'Confirmado'), ('lista_espera', 'En Lista de Espera'), ('cancelada', 'Cancelada')], default='confirmado', max_length=20, verbose_name='Estado'),
        ),
    ]
