# Generated by Django 5.0.4 on 2025-11-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace/URL'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('archivo', 'Archivo (PDF, etc.)'), ('enlace', 'Enlace/URL')], default='archivo', max_length=10, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales_cursos/'),
        ),
    ]
