# Generated by Django 5.0.4 on 2025-11-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_material_enlace_material_tipo_alter_material_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['orden', 'id_curso']},
        ),
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.IntegerField(default=0, help_text='Número que determina el orden de visualización en el index (menor número = más arriba)', verbose_name='Orden de Visualización'),
        ),
    ]
