# Generated by Django 5.2.7 on 2025-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options_curso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='edad_maxima',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad Máxima'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='cupo_maximo',
            field=models.IntegerField(default=25, verbose_name='Cupo Máximo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='edad_minima',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad Mínima'),
        ),
    ]
