# Generated by Django 5.2.7 on 2025-11-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decirlo')], max_length=1, null=True, verbose_name='Género')),
                ('ciudad_residencia', models.CharField(blank=True, choices=[('Ushuaia', 'Ushuaia'), ('Rio Grande', 'Río Grande'), ('Tolhuin', 'Tolhuin')], max_length=50, null=True, verbose_name='Ciudad de Residencia')),
                ('zona_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona/Barrio')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio Completo')),
                ('condiciones_medicas', models.TextField(blank=True, null=True, verbose_name='Condiciones Médicas/Alergias')),
                ('autorizacion_imagen', models.BooleanField(default=False, verbose_name='Autorización Uso de Imagen')),
                ('autorizacion_voz', models.BooleanField(default=False, verbose_name='Autorización Uso de Voz')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=128)),
                ('permiso_imagen', models.BooleanField(default=False)),
                ('permiso_voz', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
