# Generated by Django 5.2.7 on 2026-01-09 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_persona_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rubro', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('rechazado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_rechazadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-actualizado', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=80, null=True)),
                ('es_socio', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_empresa', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Miembro de Empresa',
                'verbose_name_plural': 'Miembros de Empresa',
                'ordering': ['-creado'],
                'unique_together': {('empresa', 'usuario')},
            },
        ),
    ]
