# Generated by Django 5.2.7 on 2026-01-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_logo_alter_empresa_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(default='', max_length=120),
        ),
    ]
