# Generated by Django 5.2.7 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_descripcion_alter_empresa_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cantidad_miembros',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='condicion_fiscal',
            field=models.CharField(blank=True, choices=[('monotributo', 'Monotributo'), ('responsable_inscripto', 'Responsable Inscripto (Unipersonal)'), ('sas', 'S.A.S. (Sociedad por Acciones Simplificada)'), ('srl', 'S.R.L. (Sociedad de Responsabilidad Limitada)'), ('sa', 'S.A. (Sociedad Anónima)'), ('cooperativa', 'Cooperativa'), ('en_formacion', 'En formación / No constituida aún')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dni_responsable_archivo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/documentos/dni/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nomina_socios_archivo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/documentos/nomina/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nomina_socios_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]

