# Generated by Django 5.2.7 on 2026-02-03 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_condicion_fiscal_y_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanHorarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('dias_semana', models.CharField(default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_horarios_empresa_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_horarios', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Plan de Horario (Empresa)',
                'verbose_name_plural': 'Planes de Horarios (Empresas)',
                'ordering': ['-actualizado', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='TurnoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('estado_asistencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('presente', 'Presente'), ('ausente', 'Ausente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('marcado_en', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=280)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empresas.empresa')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_empresa_marcados', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='empresas.planhorarioempresa')),
            ],
            options={
                'verbose_name': 'Turno (Empresa)',
                'verbose_name_plural': 'Turnos (Empresas)',
                'ordering': ['-fecha', '-hora_desde', '-creado'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'fecha', 'hora_desde', 'hora_hasta'), name='uniq_turno_empresa_fecha_horario')],
            },
        ),
    ]
