# Generated by Django 5.2.7 on 2026-02-04 03:53

from django.db import migrations, models


def forwards(apps, schema_editor):
    TurnoEmpresa = apps.get_model('empresas', 'TurnoEmpresa')
    TurnoEmpresa.objects.filter(estado_asistencia='pendiente').update(estado_asistencia=None)
    TurnoEmpresa.objects.filter(estado_asistencia='cancelado').update(estado_asistencia='ausente')
    TurnoEmpresa.objects.filter(estado_asistencia='').update(estado_asistencia=None)


def backwards(apps, schema_editor):
    TurnoEmpresa = apps.get_model('empresas', 'TurnoEmpresa')
    TurnoEmpresa.objects.filter(estado_asistencia='').update(estado_asistencia=None)


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_planhorarioempresa_turnoempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoempresa',
            name='estado_asistencia',
            field=models.CharField(blank=True, choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default=None, max_length=20, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
